# Generated by Django 4.2.14 on 2025-10-20 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codex', '0003_alter_domain_banner_image_alter_domain_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('color', models.CharField(blank=True, default='', help_text='CSS var o #hex', max_length=32)),
                ('icon', models.CharField(blank=True, default='', help_text='fa-solid fa-bolt', max_length=120)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('body', models.TextField(help_text='Contenido (puedes usar HTML simple)')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to=news.models.upload_news_media)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to=news.models.upload_news_media)),
                ('video_url', models.URLField(blank=True, default='', help_text='YouTube, Vimeo o .mp4/.webm directo')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('published', 'Publicado')], default='draft', max_length=10)),
                ('publish_at', models.DateTimeField(blank=True, help_text='Si se programa, se publicará a esta hora', null=True)),
                ('pin_home', models.BooleanField(default=False, help_text='Destacar en portada de noticias')),
                ('is_patch_notes', models.BooleanField(default=False, help_text="Marcar como 'Notas del parche'")),
                ('version', models.CharField(blank=True, default='', help_text='v1.2.0 (opcional)', max_length=40)),
                ('reading_time', models.PositiveIntegerField(default=4, help_text='Minutos estimados')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category')),
                ('gallery', models.ManyToManyField(blank=True, related_name='news_articles', to='codex.asset')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='news.tag')),
            ],
            options={
                'ordering': ['-publish_at', '-created'],
            },
        ),
    ]
