# Generated by Django 4.2.14 on 2025-10-20 00:08

import codex.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('quote', models.CharField(blank=True, help_text='Eco / frase', max_length=200)),
                ('rarity', models.CharField(choices=[('comun', 'Común'), ('raro', 'Raro'), ('epico', 'Épico'), ('mitico', 'Mítico')], default='raro', max_length=10)),
                ('bearer', models.CharField(blank=True, help_text='Portador', max_length=120)),
                ('epoch', models.CharField(blank=True, help_text='Época', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('usage', models.TextField(blank=True, help_text='Sugerencias de uso / ventajas')),
                ('image', models.ImageField(blank=True, null=True, upload_to=codex.models.upload_artifact_media)),
                ('gif', models.FileField(blank=True, null=True, upload_to=codex.models.upload_artifact_media)),
                ('video_url', models.URLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=codex.models.upload_asset_file)),
                ('kind', models.CharField(choices=[('image', 'Imagen'), ('gif', 'GIF'), ('video', 'Video')], default='image', max_length=10)),
                ('caption', models.CharField(blank=True, max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('role', models.CharField(blank=True, help_text='Clase / rol', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('playable', models.BooleanField(default=False)),
                ('sprite_still', models.ImageField(blank=True, help_text='Sprite estático', null=True, upload_to=codex.models.upload_character_image)),
                ('sprite_gif', models.FileField(blank=True, help_text='Animación principal (GIF)', null=True, upload_to=codex.models.upload_character_image)),
                ('sprite_sheet', models.ImageField(blank=True, help_text='Sprite sheet (opcional)', null=True, upload_to=codex.models.upload_character_image)),
                ('sprite_meta', models.JSONField(blank=True, help_text='{"frame_w":32,"frame_h":32,"fps":12} (opcional)', null=True)),
                ('video_url', models.URLField(blank=True)),
                ('image_full', models.ImageField(blank=True, null=True, upload_to=codex.models.upload_character_image)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=codex.models.upload_domain_cover)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to=codex.models.upload_domain_banner)),
                ('color', models.CharField(blank=True, help_text='CSS variable o #hex (opcional)', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Clase de Font Awesome (e.g. fa-solid fa-fire)', max_length=80)),
                ('video_url', models.URLField(blank=True, help_text='Enlace a .mp4/.webm (opcional)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('behavior', models.TextField(blank=True, help_text='Comportamiento / ataques')),
                ('sprite_still', models.ImageField(blank=True, null=True, upload_to=codex.models.upload_enemy_image)),
                ('sprite_gif', models.FileField(blank=True, null=True, upload_to=codex.models.upload_enemy_image)),
                ('image_full', models.ImageField(blank=True, null=True, upload_to=codex.models.upload_enemy_image)),
                ('video_url', models.URLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enemies', to='codex.domain')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=codex.models.upload_trap_image)),
                ('gif', models.FileField(blank=True, null=True, upload_to=codex.models.upload_trap_image)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traps', to='codex.domain')),
            ],
            options={
                'ordering': ['domain__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=codex.models.upload_asset_file)),
                ('video_url', models.URLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lore', to='codex.domain')),
                ('gallery', models.ManyToManyField(blank=True, to='codex.asset')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='comas: movilidad,combate,secretos', max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=codex.models.upload_asset_file)),
                ('read_time', models.PositiveIntegerField(default=4, help_text='Minutos estimados')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides', to='codex.domain')),
                ('related_artifacts', models.ManyToManyField(blank=True, to='codex.artifact')),
                ('related_characters', models.ManyToManyField(blank=True, to='codex.character')),
                ('related_enemies', models.ManyToManyField(blank=True, to='codex.enemy')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='EnemyAnimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('gif', models.FileField(blank=True, null=True, upload_to=codex.models.upload_enemy_media)),
                ('mp4', models.FileField(blank=True, null=True, upload_to=codex.models.upload_enemy_media)),
                ('webm', models.FileField(blank=True, null=True, upload_to=codex.models.upload_enemy_media)),
                ('order', models.PositiveIntegerField(default=0)),
                ('loop', models.BooleanField(default=True)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animations', to='codex.enemy')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CharacterAnimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('gif', models.FileField(blank=True, null=True, upload_to=codex.models.upload_character_media)),
                ('mp4', models.FileField(blank=True, null=True, upload_to=codex.models.upload_character_media)),
                ('webm', models.FileField(blank=True, null=True, upload_to=codex.models.upload_character_media)),
                ('sprite_sheet', models.ImageField(blank=True, null=True, upload_to=codex.models.upload_character_media)),
                ('sprite_meta', models.JSONField(blank=True, help_text='{"frame_w":32,"frame_h":32,"fps":12}', null=True)),
                ('loop', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animations', to='codex.character')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='codex.domain'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='codex.domain'),
        ),
    ]
