# Generated by Django 4.2.14 on 2025-10-20 00:52

import codex.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=codex.models.upload_codex),
        ),
        migrations.AlterField(
            model_name='domain',
            name='color',
            field=models.CharField(blank=True, default='', help_text='CSS variable o #hex (ej. var(--tiempo) o #00ff00)', max_length=32),
        ),
        migrations.AlterField(
            model_name='domain',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=codex.models.upload_codex),
        ),
        migrations.AlterField(
            model_name='domain',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Clase de Font Awesome (ej. fa-solid fa-hourglass-half)', max_length=100),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='domain',
            name='short_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='domain',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='URL http(s) a .mp4/.webm (opcional)'),
        ),
    ]
