# Generated by Django 4.2.14 on 2025-10-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0002_alter_domain_banner_image_alter_domain_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='codex/domains/'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='color',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='domain',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='codex/domains/'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='domain',
            name='slug',
            field=models.SlugField(max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
