# Generated by Django 4.2.14 on 2025-11-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codex', '0003_alter_domain_banner_image_alter_domain_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artifact',
            options={'ordering': ['name'], 'verbose_name': 'Emblema', 'verbose_name_plural': 'Emblemas'},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name'], 'verbose_name': 'Personaje', 'verbose_name_plural': 'Personajes'},
        ),
        migrations.AlterModelOptions(
            name='characteranimation',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Animación de personaje', 'verbose_name_plural': 'Animaciones de personaje'},
        ),
        migrations.AlterModelOptions(
            name='enemy',
            options={'ordering': ['name'], 'verbose_name': 'Enemigo', 'verbose_name_plural': 'Enemigos'},
        ),
        migrations.AlterModelOptions(
            name='enemyanimation',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Animación de enemigo', 'verbose_name_plural': 'Animaciones de enemigo'},
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['-updated', '-created', 'title'], 'verbose_name': 'Guía', 'verbose_name_plural': 'Guías'},
        ),
        migrations.AlterModelOptions(
            name='loreentry',
            options={'ordering': ['title'], 'verbose_name': 'Historia', 'verbose_name_plural': 'Historias'},
        ),
        migrations.AlterModelOptions(
            name='trap',
            options={'ordering': ['domain__name', 'title'], 'verbose_name': 'Trampa', 'verbose_name_plural': 'Trampas'},
        ),
        migrations.AddField(
            model_name='guide',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
