# Generated by Django 4.2.14 on 2025-12-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_comment_parent_postreaction_commentreaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='reaction',
            field=models.CharField(choices=[('like', 'Me gusta'), ('fire', '🔥 Épico'), ('gg', 'GG')], default='like', max_length=16),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='reaction',
            field=models.CharField(choices=[('like', 'Me gusta'), ('fire', '🔥 Épico'), ('gg', 'GG')], default='like', max_length=16),
        ),
    ]
