# Generated by Django 4.2.14 on 2025-10-19 21:45

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_avatar)),
                ('gamertag', models.CharField(blank=True, max_length=32)),
                ('bio', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=48)),
                ('country', models.CharField(blank=True, max_length=48)),
                ('fav_artifact', models.CharField(blank=True, choices=[('artiempo', 'Reloj Fractal (Tiempo)'), ('arniebla', 'Cristal de Niebla (Niebla)'), ('arfuego', 'Antorcha Eterna (Cenizas)'), ('arviento', 'Pluma Etérea (Vientos)'), ('arpiedra', 'Runa de Tierra (Piedra)')], max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=240)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
